name: Conjur Secret Test

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Import Secrets using CyberArk Conjur Secret Fetcher Action
        uses: cyberark/conjur-action@v2.0.5
        with:
          url: ${{ secrets.CONJUR_URL }}
          account: conjur
          host_id: ${{ secrets.CONJUR_USERNAME }}
          api_key: ${{ secrets.CONJUR_API_KEY }}
          secrets: >-
            vault01/secrets/Postgresql-DB/app01/username|db_username;
            vault01/secrets/Postgresql-DB/app01/password|db_password

      - name: Use the secrets
        run: |
          echo "Connecting to PostgreSQL..."
          psql -U $db_username -p $db_password -h 172.15.10.100
          echo "Successfully connected to PostgreSQL!"

# test run - 3 March 2026